name: Build and release

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Cleanup working dir
        run: rm -rfv ./*

      - name: Clone repo (needed for contribs)
        run: git clone https://github.com/OXRS-IO/OXRS-IO-WEBSITE.git ./

      - name: NPM I
        run: npm ci

      - name: NPM Build
        run: npm run build
      
      - name: Move dist dir for release
        run: mv ./docs/.vuepress/dist ./dist

      - name: Custom domain - github pages
        run: echo 'oxrs.io' > ./dist/CNAME
      
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
